services:
  - type: web
    name: teorify-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
